version: '3'

services:
  worker:
    image: ${locust_image}
    tty: true
    volumes:
      - ${locust_workspace}/${JOB_NAME}:/mnt/locust/${JOB_NAME}
    command: locust -f /mnt/locust/${JOB_NAME}/${locust_main} --worker --master-host=${mainhost}
