version: '3'

services:
  master:
    build:
      context: ./
      args:
        VER: ${JOB_NAME}
    image: ${locust_image}
    tty: true
    volumes:
      - /opt/locust/${JOB_NAME}:/mnt/locust/${JOB_NAME}
    ports:
      - "8089:8089"
      - "5557:5557"
    command: locust -f /mnt/locust/${JOB_NAME}/locustfile.py -T ${appointedCase}  --master

  worker:
    image: ${locust_image}
    tty: true
    volumes:
      - /opt/locust/${JOB_NAME}:/mnt/locust/${JOB_NAME}
    command: locust -f /mnt/locust/${JOB_NAME}/locustfile.py -T ${appointedCase} --worker --master-host=master
