version: '3'

services:
  worker:
    image: ${locust_image}
    tty: true
    volumes:
      - /opt/locust/${JOB_NAME}:/mnt/locust/${JOB_NAME}
    command: locust -f /mnt/locust/${JOB_NAME}/locustfile.py --worker --master-host=${mainhost}
